"""Init migration

Revision ID: 8f456351fcbc
Revises: 
Create Date: 2023-03-01 16:42:41.460709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f456351fcbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('firstname', sa.String(length=60), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('vk_id')
    )
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_table('bot_search_results',
    sa.Column('who_looking_vk_id', sa.Integer(), nullable=False),
    sa.Column('who_found_vk_id', sa.Integer(), nullable=False),
    sa.Column('is_viewed', sa.Boolean(), nullable=True),
    sa.Column('is_favorited', sa.Boolean(), nullable=True),
    sa.Column('is_black_listed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('favorited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('black_listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['who_found_vk_id'], ['contacts.vk_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['who_looking_vk_id'], ['contacts.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('who_looking_vk_id', 'who_found_vk_id')
    )
    op.create_index(op.f('ix_bot_search_results_created_at'), 'bot_search_results', ['created_at'], unique=False)
    op.create_index(op.f('ix_bot_search_results_is_black_listed'), 'bot_search_results', ['is_black_listed'], unique=False)
    op.create_index(op.f('ix_bot_search_results_is_favorited'), 'bot_search_results', ['is_favorited'], unique=False)
    op.create_index(op.f('ix_bot_search_results_is_viewed'), 'bot_search_results', ['is_viewed'], unique=False)
    op.create_table('photos',
    sa.Column('vk_id', sa.Integer(), nullable=False),
    sa.Column('vk_photo_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vk_id'], ['contacts.vk_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('vk_id', 'vk_photo_id')
    )
    op.create_index(op.f('ix_photos_created_at'), 'photos', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_created_at'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_bot_search_results_is_viewed'), table_name='bot_search_results')
    op.drop_index(op.f('ix_bot_search_results_is_favorited'), table_name='bot_search_results')
    op.drop_index(op.f('ix_bot_search_results_is_black_listed'), table_name='bot_search_results')
    op.drop_index(op.f('ix_bot_search_results_created_at'), table_name='bot_search_results')
    op.drop_table('bot_search_results')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_table('contacts')
    # ### end Alembic commands ###
